### ISSUE TITLE
config and execute GREATER

### ISSUE THREAD

**Issue by iriscodinggit** [Adrian-REH/minishell#2]
Es necesario hacer estas pruebas para pasar GREATER:

### multiples GREATER:

```c
cmd > cmd > cmd > ... > cmd
```
- [ ] completed

### multiples GREATER and not end:

```c
cmd > cmd > cmd > ... >
```
- [ ] completed
### One GREATER:

```c
cmd > cmd 
```
- [ ] completed
### One GREATER and not end:

```c
cmd >
```
- [ ] completed

**Comment by iriscodinggit** [comment]
En la primera prueba (multiples GREATER) hay un error: interpreta archivos como si fueran comandos. Ejemplo:

`echo hello > file1`

En este comando, en vez de redireccionar hello a file, se muestra el siguiente error: **command not found file1**.

**Comment by iriscodinggit** [comment]
En la segunda prueba (multiples GREATER and not end) hay un error: cuando no se escribe un comando después de >, debería dar un parse error como en bash (zsh: parse error near `\n'). Ejemplo:

`ls >`

En este comando, en vez de mostrar un error por estar incompleto, ejecuta ls de forma normal. Debería mostrar un error.

**Comment by iriscodinggit** [comment]
En la tercera prueba (One GREATER) ocurre el mismo error que en la primera prueba: interpreta el nombre de archivos como si fueran comandos. Ejemplo:

echo hello > file1 

En este comando, en vez de redireccionar hello a file, se muestra el siguiente error: command not found file1.

**Comment by Adrian-REH** [comment]
Gracias!, estoy revisando todas las redirecciones, te mantendre al tanto

**Comment by Adrian-REH** [comment]
Problema solucionado, hubo un error en la identificacion del operador ">" greter, que es la posicion 0 en el array, la condicion de configuracion cuando ve que el siguiente estado es NULL(0), identifica que no hay ningun operador luego, y por tanto obliga a olvidar el operador para ejecutar el comando sin operadores.
